### ISSUE TITLE
Riesgos en el ciclo 2

### ISSUE THREAD

**Issue by CesarF** [MISO4203-201520/mp-app#7]
Para el ciclo 2 se deben manejar únicamente los riesgos que tuvimos presentes en el ciclo 1? o debemos agregar nuevos riesgos? o ya hay algunos definidos (aunque no los encontramos).

Mil gracias

**Comment by rcasalla** [comment]
Los del ciclo 1 y si identifican más al que deben hacer mitigación lo pueden agregar
